### ISSUE TITLE
libcbm Source and HomeAssistant

### ISSUE THREAD

**Issue by kiwi64ajs** [micolous/cbus#11]
Hi Guys,
I'm just working through configuring HomeAssistant on a RPi 4 and as I have a Clipsal C-Bus system in my house I was researching the options to integrate with C-Bus and found this project.

I have a few USB to C-Bus adaptors and a Network to C-Bus adaptor so I can do some testing if that was helpful.

Also just looking at the main project page I noticed that you said the libcbm code was X86 and closed source. Are you aware Clipsal posted their source code on SourceForge in 2009 here: https://sourceforge.net/projects/cbusmodule/files/source/ It has some docs as well.

Anyway looking forward to experimenting with this project and integrating C-Bus to HA

Regards

Alex Shepherd
Hamilton New Zealand

**Comment by micolous** [comment]
Thanks for the tip, I wasn't aware that the code was actually released.  I'll update the documentation.
