### ISSUE TITLE
Passing light names from CBus via cmqttd

### ISSUE THREAD

**Issue by stavlocker** [micolous/cbus#20]
Hello!
First off, **great** work with this repo. Thanks a lot.

It would be mighty helpful if when using cmqttd the names of the lights passed wouldn't be "CBus Light XXX", but rather the name configured in CBus.

**Comment by micolous** [comment]
I agree, that would be nice to have, and it's been on the list for a while... 😄 

I'm pretty sure the data is available from the units in some form.

**Comment by micolous** [comment]
I've been playing around with this some more, and it seems much more limited.

There are two possible approaches:

1. **Use CBZ (Toolkit) group names.**  This relies on having the project files from the installer, and meaningful names being configured in the project.

   While it's possible to use Toolkit to download the configuration from a network _without_ an existing project file, user-defined group names aren't saved anywhere on the network.

   This isn't useful for someone who moves into a building with C-Bus _already_ installed, or who purchases a PCI/CNI after-the-fact to use with Home Assistant.

2. **Use DLT labels.**  According to the protocol docs, there's ways to set these labels, but there isn't an obvious way to "fetch" the labels from an existing network.

   I don't have any devices which support DLT labels, so while I can program them, and the units accept the command (per spec), it silently discards this information and is not recovered when deleting and re-transferring a project from the network.

   _This is pretty much a dead end, so there's no way to auto-discover group names from DLT._

I've written some code in the past to dump data out of Toolkit projects, so I think the solution is going to be adding a command-line flag to _optionally_ read a CBZ on start-up, and use it as a source of group names.
