### ISSUE TITLE
Rookie Cbus Knowledge Error

### ISSUE THREAD

**Issue by BUSTERCJB** [micolous/cbus#21]
I had a lack of understanding about how messages and transferred cross network.

**Comment by micolous** [comment]
Sorry, `cmqttd` doesn't support multiple networks.  The lower level APIs probably support it, but it'll be untested.  I don't have any bridge units, or access to an installation that uses it, and AFAIK this is typically only used by corporate installations.

You may be able to work around it if I get to supporting other applications (#19), but that might significantly require reconfiguring your network.

**Comment by BUSTERCJB** [comment]
cmqttd actually works quite well across multiple networks. The only issue is, due to the CBUS network protocols, the bridge isolates messages "crossing" between networks, unless required. This means that if I turn address 001 on via home assistant, and if there is a relay on 001, on the network which isn't connected to the PCI, it will turn on. However, if I turn it off, using a switch on the non-PCI network, then cmqttd will assume that the light is still on, as the CBUS protocol doesn't let the turn off message cross to the PCI network, as it isn't necessary for the action to occur. 

I haven't tested being able to turn switches on the Non-PCI network, and seeing if they turn on in the CBUS toolkit. I will experiment with this if I have the chance. If the state changes are reflected in CBUS toolkit, then it means maybe something needs to be programmed to support it. 

Thanks for all of your hard work!!!
