### ISSUE TITLE
Fatal error: protocol.data_received()

### ISSUE THREAD

**Issue by RobRam** [micolous/cbus#29]
Hi Michael

Thanks for the effort in getting CBus to work in HA, it's much appreciated.

I'm running cmqttd on an Odroid N2+ in Debian 11 and Home Assistant on the same device in Supervised mode. (I bought the odroid specifically to run cmqttd).

Everything seemed to install correctly, but after running:
`cmqttd --broker-address 192.168.1.23 --broker-disable-tls --tcp 192.168.1.22:10001`

I get:
```
2021-11-26 12:34:55,461 Transport security disabled!
2021-11-26 12:34:55,469 Connected to MQTT broker
2021-11-26 12:34:55,574 Fatal error: protocol.data_received() call failed.
protocol: <cbus.daemon.cmqttd.CBusHandler object at 0xffff9cf66d60>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.9/dist-packages/cbus-0.2-py3.9.egg/cbus/protocol/buffered_protocol.py", line 72, in data_received
    raise ValueError('Received data exceeds size limit '
ValueError: Received data exceeds size limit (256 bytes)
```

Any ideas ?... I'd really appreciate any help.

Many thanks
Rob

**Comment by RobRam** [comment]
I've also tried using a PCI (via a Prolific Technology, Inc. USB-Serial Controller) and the command runs and hangs:
```
sudo cmqttd --broker-address 192.168.1.23 --broker-disable-tls --serial /dev/ttyUSB0
2021-12-14 18:05:55,507 Transport security disabled!
2021-12-14 18:05:55,511 Connected to MQTT broker
```

it hangs here, and ctrl-C breaks it and reports:
```
Traceback (most recent call last):
  File "/usr/local/bin/cmqttd", line 33, in <module>
    sys.exit(load_entry_point('cbus==0.2', 'console_scripts', 'cmqttd')())
  File "/usr/local/lib/python3.9/dist-packages/cbus-0.2-py3.9.egg/cbus/daemon/cmqttd.py", line 474, in main
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

I've double checked that the serial port driver is installed in Debian and working on ttyUSB0, and I can connect to the CBUS PCI using CBUS Toolkit in Windows over the same USB/Serial cable/connection.
 - so the physical cable and connection work on Windows.
 - the Linux usb/serial driver (v5.15.5) 'seems' to be working, and is reporting as linked to ttyUSB0, but I have no way to confirm that it is correctly installed and communicating with the PCI.
 
So I'm a little at a loss on how to test the usb/serial connection to the PCI directly in Debian 11.
...or to further figure out where the problem(s) is/are.

Any ideas ?... again, I'd really appreciate any help.

Many thanks
Rob

**Comment by Nik19792000** [comment]
Try running it as docker container. That worked well for me. I followed these instructions:

Installation:
- https://community.home-assistant.io/t/mqtt-discovery-with-cmqttd/204673/6
- https://cbus.readthedocs.io/en/latest/cmqttd.html#cmqttd-docker
- Command to start: docker run -dit --name cbus --restart=always --device /dev/ttyUSB0 --network hassio -e "TZ=Asia/Singapore" cmqttd cmqttd -s /dev/ttyUSB0 -b core-mosquitto --broker-disable-tls --log-file cbus.log --verbosity DEBUG --broker-disable-tls --broker-auth MQTTcredentials

**Comment by RobRam** [comment]
Nice, that --broker-auth MQTTcredentials did the trick without having to run it in docker.
Now I just need to figure out how to run it on boot.

**Comment by RobRam** [comment]
Sorted... I avoided the docker route and got cmqttd running on startup as a service using systemd instead.
The key really was the mqqt user:password as indicated on:
https://community.home-assistant.io/t/mqtt-discovery-with-cmqttd/204673/6
I implemented the user:pass in the mqqt yaml config rather than the HA user, which worked just as well.
