### ISSUE TITLE
Access to OpenCbus docs

### ISSUE THREAD

**Issue by MickMake** [micolous/cbus#37]
Not really an issue, but do you have a copy of the OpenCBus docs from clipsal?

They seem to have pulled them from their website completely.

**Comment by Nick-Adams-AU** [comment]
See if this works:

https://web.archive.org/web/20180221063055/http://training.clipsal.com/downloads/OpenCBus/OpenCBusProtocolDownloads.html

**Comment by MickMake** [comment]
Thanks mate. Was using http://updates.clipsal ... and couldn't find it on archive.org.
