### ISSUE TITLE
MQTT credentials

### ISSUE THREAD

**Issue by PianSom** [micolous/cbus#9]
Hi - nice work!

As far as I can tell, it is not possible to pass login credentials to the MQTT broker. Any chance of implementing this?

**Comment by micolous** [comment]
I've merged my `python3` and `python3-asyncio` branches to `master` now; the `python3-asyncio` branch has support for this.

Make a text file with two lines: on the first line write the username, on the second line write the password.  Then give the path of this file to `cmqttd` with the `--broker-auth` option.

Admittedly, TLS and Authentication is largely untested at this point, but they delegate the `paho.mqtt` library.

**Comment by micolous** [comment]
Now properly documented here: https://cbus.readthedocs.io/en/latest/cmqttd.html#cmdoption-cmqttd-broker-auth
